---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-project  # Changed to lowercase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-project  # Changed to lowercase
  template:
    metadata:
      labels:
        app: healthcare-project  # Changed to lowercase
    spec:
      containers:
        - name: healthcare-project  # Fixed typo in name ("projeect" → "project")
          image: danishdockerhub/staragile-project-healthcare:v1
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-project  # Changed to lowercase
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: healthcare-project  # Changed to lowercase
